version: '3'

services:
  web:
    build: .
    command: gunicorn --reload -b 0.0.0.0:8000 --workers 3 config.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:latest
