apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: django-web-server:latest
        ports:
        - containerPort: 8000
        env:
        - name: CELERY_BROKER_URL
          value: redis://redis:6379
        - name: CELERY_RESULT_BACKEND
          value: django-db
